---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: clang-format
  name: clang-format
  entry: clang-format-hook
  description: Formats C/CPP code
  files: \.(c|cc|cxx|cpp|h|hpp|hxx|m)$
  language: python
- id: clang-tidy
  name: clang-tidy
  entry: clang-tidy-hook
  description: Find warnings/errors in C/CPP code
  files: \.(c|cc|cxx|cpp|h|hpp|hxx|m)$
  language: python
- id: oclint
  name: oclint
  entry: oclint-hook
  description: Find warnings/errors in C/CPP code
  files: \.(c|cc|cxx|cpp|h|hpp|hxx|m)$
  language: python
- id: uncrustify
  name: uncrustify
  entry: uncrustify-hook
  description: Find warnings/errors in C/CPP code
  files: \.(c|cc|cxx|cpp|h|hpp|hxx|m)$
  language: python
