---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: clang-format
  name: clang-format
  entry: hooks/clang-format
  description: Formats C/CPP code
  files: [c, c++]
  language: script
  additional_dependencies: [clang-format]
- id: clang-tidy
  name: clang-tidy
  entry: hooks/clang-tidy
  description: Find warnings/errors in C/CPP code
  files: [c, c++]
  language: script
  additional_dependencies: [clang-tidy]
- id: oclint
  name: oclint
  entry: hooks/oclint
  description: Find warnings/errors in C/CPP code
  files: [c, c++]
  language: script
  additional_dependencies: [oclint]
