#!/usr/bin/env bash
# Wrapper script for clang-tidy

. hooks/utils

check_exists clang-tidy
# Split text into an array of args that can be passed into clang-tidy
IFS=" " read -r -a args <<< "$(clean_args "$@")"
clang-tidy "${args[@]}"
return $?
