#!/usr/bin/env bash
# Wrapper script for clang-format
CMD="clang-format"
if [ -z "$(command -v $CMD)" ]; then
	echo -e "ERR: $CMD not found.\nMake sure to install $CMD and add it to your path."
	echo -e "For more info: https://github.com/pocc/pre-commit-hooks#prerequisites"
	exit 1
fi

# Get the file argument if one exists.
for arg in "$@"; do
	if [ -e "$arg" ]; then
		filename="$arg"
	fi
done

if [ -z "$filename" ]; then
	echo "ERR: No file arg found. args =" "$@"
	exit 1
fi

# If there are differences, this script will fail (and pre-commit should show this)
if [[ " $* " == *" -i "* ]]; then
	# Here, diff compares what the file is before and after transform
	diff "$filename" <(clang-format "$@"; cat "$filename")
else
	# Otherwise clang-format should send output to stdout, and can be compared
	diff "$filename" <(clang-format "$@")
fi
