#!/usr/bin/env bash
# Wrapper script for clang-format
CMD="clang-format"
if [ -z "$(command -v $CMD)" ]; then
	echo -e "ERR: $CMD not found.\nMake sure to install $CMD and add it to your path."
	echo -e "For more info: https://github.com/pocc/pre-commit-hooks#prerequisites"
	exit 1
fi

# Get the file argument if one exists.
for arg in "$@"; do
	argpath="$(realpath "$arg")"
	if test -f "$argpath"; then
		filepath="$argpath"
	fi
done

if [ -z "$filepath" ]; then
	echo "ERR: No file arg found. args =" "$@"
	exit 1
fi

# pre-commit will fail if there are file changes due to formatting if the user
# enters arg `-i` (change in place).
# If there are differences, this script will fail (and pre-commit should show this)
diff "$filepath" <(clang-format "$@")
