#!/bin/sh
# Wrapper script for clang-tidy
set -eu
readonly DEBUG=${DEBUG:-unset}
if [ "${DEBUG}" != unset ]; then
  set -x
fi

. hooks/utils

# hook args exist that need to be acted upon
clang-tidy $(clean_args "$@")

