#!/usr/bin/env bash
set -eu
readonly DEBUG=${DEBUG:-unset}
if [ "${DEBUG}" != unset ]; then
  set -x
fi

# oclint can generate plist files that are unnecessary
pwd_files="$(ls)"
oclint "$@" -- -DCMAKE_EXPORT_COMPILE_COMMANDS
tempfiles="$(comm -3 <( echo "$pwd_files" | tr ' ' '\n' ) <( find * | tr ' ' '\n' ) --nocheck-order | grep .plist)"
rm "$tempfiles"

